admin:
  username: admin
  password: pass
  #secret_file: path_to_yaml
authz:
  disable_mask: false
  show_whitelist: true
  show_admin: false
smtp:
  foo@example.com:
    address: localhost
    port: 25
    enable_starttls_auto: false
default_recent_days: 14
only_searched_bounce_mails: true
digest: sha1
#mail_link: "https://localhost:9200/_plugin/kibana/#/discover?_a=(index:'maillog-*',query:(query_string:(query:'digest:%{digest}')))"
header_links:
  "Example Domain": http://example.com/
  "Bounce Reason": http://libsisimai.org/en/reason/
#blacklisted_label_filter: |
#  proc do |m|
#    not m.softbounce or m.reason == "filtered"
#  end
#whitelist_callback:
#  whitelisted: path_to_script
#  unwhitelisted: path_to_script
#shorten_stats: false
#bounce_over:
#  buffer: 0
#omniauth:
#  google_client_id: ~
#  google_client_secret: ~
#  hd:
#    - example.com
#  allow_users:
#    - foo@example.com
#    - bar@example.com
#status:
#  interval: 60
